import { FoodItem, Hospital, Recipe } from './types';

export const MOCK_FOODS: FoodItem[] = [
  { id: '1', name: 'Apple', calories: 52, protein: 0.3, carbs: 13.8, fats: 0.2, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Fruit' },
  { id: '2', name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fats: 3.6, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Protein' },
  { id: '3', name: 'Brown Rice', calories: 111, protein: 2.6, carbs: 23, fats: 0.9, serving: '100 g cooked', baseQuantity: 100, unit: 'g', category: 'Grains' },
  { id: '4', name: 'Egg', calories: 78, protein: 6.3, carbs: 0.6, fats: 5.3, serving: '1 large egg', baseQuantity: 1, unit: 'piece', category: 'Protein' },
  { id: '5', name: 'Oatmeal', calories: 68, protein: 2.4, carbs: 12, fats: 1.4, serving: '100 g cooked', baseQuantity: 100, unit: 'g', category: 'Breakfast' },
  { id: '6', name: 'Banana', calories: 89, protein: 1.1, carbs: 22.8, fats: 0.3, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Fruit' },
  { id: '7', name: 'Salmon', calories: 208, protein: 20, carbs: 0, fats: 13, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Protein' },
  { id: '8', name: 'Broccoli', calories: 34, protein: 2.8, carbs: 7, fats: 0.4, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Vegetable' },
  { id: '9', name: 'Tofu', calories: 144, protein: 15.7, carbs: 3.9, fats: 8.7, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Plant Protein' },
  { id: '10', name: 'Paneer', calories: 265, protein: 18.3, carbs: 1.2, fats: 20.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Dairy' },
  { id: '11', name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fats: 0.4, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Dairy' },
  { id: '12', name: 'Milk', calories: 61, protein: 3.2, carbs: 4.8, fats: 3.3, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '13', name: 'Orange Juice', calories: 45, protein: 0.7, carbs: 10.4, fats: 0.2, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '14', name: 'Black Coffee', calories: 2, protein: 0.3, carbs: 0, fats: 0, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '15', name: 'Almonds', calories: 579, protein: 21.2, carbs: 21.6, fats: 49.9, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Snacks' },
  { id: '16', name: 'Peanut Butter', calories: 588, protein: 25, carbs: 20, fats: 50, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Spreads' },
  { id: '17', name: 'Whole Wheat Bread', calories: 247, protein: 13, carbs: 41, fats: 4.2, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Bakery' },
  { id: '18', name: 'Protein Shake', brand: 'Optimum Nutrition Gold Standard', calories: 120, protein: 24, carbs: 3, fats: 1.5, serving: '1 scoop', baseQuantity: 1, unit: 'piece', category: 'Supplements', isPackaged: true, notes: 'Popular whey protein brand' },
  { id: '19', name: 'Potato Chips', brand: "Lay's Classic", calories: 536, protein: 6.6, carbs: 53, fats: 34, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Snacks', isPackaged: true, notes: 'Brand reference for common salted chips values' },
  { id: '20', name: 'Nacho Chips', brand: 'Doritos Nacho Cheese', calories: 500, protein: 6.7, carbs: 63.3, fats: 23.3, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Snacks', isPackaged: true },
  { id: '21', name: 'Milk Chocolate', brand: 'Cadbury Dairy Milk', calories: 534, protein: 7.3, carbs: 59.4, fats: 29.7, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Sweets', isPackaged: true },
  { id: '22', name: 'Dark Chocolate', brand: 'Amul 55% Dark', calories: 546, protein: 7.8, carbs: 49, fats: 35, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Sweets', isPackaged: true },
  { id: '23', name: 'Instant Noodles', brand: 'Maggi Masala Noodles', calories: 457, protein: 8.6, carbs: 64.6, fats: 18.7, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Meals', isPackaged: true },
  { id: '24', name: 'Chocolate Cookies', brand: 'Oreo Original', calories: 480, protein: 4.7, carbs: 71, fats: 19, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Snacks', isPackaged: true },
  { id: '25', name: 'Soft Drink', brand: 'Coca-Cola', calories: 42, protein: 0, carbs: 10.6, fats: 0, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Packaged Drinks', isPackaged: true },
  { id: '26', name: 'Sports Drink', brand: 'Gatorade Orange', calories: 25, protein: 0, carbs: 6, fats: 0, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Packaged Drinks', isPackaged: true },
  { id: '27', name: 'Mango Drink', brand: 'Tropicana Mango Delight', calories: 54, protein: 0.2, carbs: 13.3, fats: 0, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Packaged Drinks', isPackaged: true },
  { id: '28', name: 'Ice Cream', brand: 'Amul Vanilla Tub', calories: 207, protein: 3.5, carbs: 24, fats: 10.9, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Dessert', isPackaged: true },
  { id: '29', name: 'Cheese Slice', brand: 'Britannia Cheese Slice', calories: 308, protein: 18, carbs: 8, fats: 22, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Dairy', isPackaged: true },
  { id: '30', name: 'Granola Bar', brand: 'Yoga Bar Nuts & Seeds', calories: 450, protein: 11, carbs: 48, fats: 22, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Snacks', isPackaged: true },
  { id: '31', name: 'Curd', calories: 61, protein: 3.5, carbs: 4.7, fats: 3.3, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Dairy' },
  { id: '32', name: 'Lassi', calories: 85, protein: 3.1, carbs: 12, fats: 2.8, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Indian Drinks' },
  { id: '33', name: 'Masala Chai', calories: 45, protein: 1.2, carbs: 6.5, fats: 1.5, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Indian Drinks' },
  { id: '34', name: 'Buttermilk', calories: 40, protein: 2.2, carbs: 4.8, fats: 1.3, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Indian Drinks' },
  { id: '35', name: 'Tender Coconut Water', calories: 19, protein: 0.7, carbs: 3.7, fats: 0.2, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '36', name: 'Roti', calories: 297, protein: 9.6, carbs: 46.4, fats: 7.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Staples' },
  { id: '37', name: 'Plain Rice', calories: 130, protein: 2.7, carbs: 28, fats: 0.3, serving: '100 g cooked', baseQuantity: 100, unit: 'g', category: 'Indian Staples' },
  { id: '38', name: 'Jeera Rice', calories: 168, protein: 3.1, carbs: 30, fats: 4, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Staples' },
  { id: '39', name: 'Dal Tadka', calories: 130, protein: 6.5, carbs: 16, fats: 4.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '40', name: 'Rajma Curry', calories: 140, protein: 6.8, carbs: 18, fats: 4.2, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '41', name: 'Chole', calories: 164, protein: 7.4, carbs: 21, fats: 5.3, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '42', name: 'Palak Paneer', calories: 180, protein: 8.4, carbs: 6.5, fats: 13.2, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '43', name: 'Paneer Butter Masala', calories: 265, protein: 8, carbs: 9, fats: 22, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '44', name: 'Chicken Curry', calories: 210, protein: 17, carbs: 5, fats: 14, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '45', name: 'Butter Chicken', calories: 290, protein: 15, carbs: 7, fats: 22, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '46', name: 'Biryani', calories: 180, protein: 6.5, carbs: 22, fats: 7.2, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '47', name: 'Veg Pulao', calories: 170, protein: 3.8, carbs: 26, fats: 5.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '48', name: 'Poha', calories: 130, protein: 2.6, carbs: 24, fats: 2.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Breakfast' },
  { id: '49', name: 'Upma', calories: 120, protein: 3, carbs: 18, fats: 3.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Breakfast' },
  { id: '50', name: 'Idli', calories: 58, protein: 2, carbs: 12, fats: 0.4, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Breakfast' },
  { id: '51', name: 'Plain Dosa', calories: 133, protein: 3.9, carbs: 15.1, fats: 5.3, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Breakfast' },
  { id: '52', name: 'Masala Dosa', calories: 190, protein: 4.8, carbs: 24, fats: 8.2, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Breakfast' },
  { id: '53', name: 'Sambar', calories: 70, protein: 2.9, carbs: 9.5, fats: 2.1, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Indian Main Course' },
  { id: '54', name: 'Coconut Chutney', calories: 150, protein: 2.1, carbs: 7, fats: 12.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sides' },
  // Duplicate entry removed
  { id: '56', name: 'Pakora', calories: 290, protein: 6.5, carbs: 22, fats: 19, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Snacks' },
  { id: '57', name: 'Pav Bhaji', calories: 180, protein: 4.5, carbs: 21, fats: 7.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
  { id: '58', name: 'Vada Pav', calories: 286, protein: 6.8, carbs: 34, fats: 13, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Street Food' },
  { id: '59', name: 'Pani Puri', calories: 180, protein: 4.2, carbs: 29, fats: 5.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
  { id: '60', name: 'Aloo Paratha', calories: 260, protein: 6.1, carbs: 32, fats: 12, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Breakfast' },
  { id: '61', name: 'Plain Paratha', calories: 300, protein: 7, carbs: 40, fats: 12, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Staples' },
  { id: '62', name: 'Khichdi', calories: 105, protein: 3.8, carbs: 18, fats: 1.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '63', name: 'Gulab Jamun', calories: 380, protein: 4.6, carbs: 48, fats: 18, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '64', name: 'Jalebi', calories: 459, protein: 4.3, carbs: 59, fats: 23, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '65', name: 'Rasgulla', calories: 186, protein: 3.5, carbs: 41, fats: 0.2, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '66', name: 'Kaju Katli', calories: 460, protein: 8.2, carbs: 50, fats: 24, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '67', name: 'Momos', calories: 190, protein: 7.5, carbs: 24, fats: 6.4, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Street Food' },
  { id: '68', name: 'Pizza Slice', brand: 'Domino’s Margherita', calories: 270, protein: 11, carbs: 33, fats: 10, serving: '1 slice', baseQuantity: 1, unit: 'piece', category: 'Fast Food', isPackaged: true },
  { id: '69', name: 'Burger', brand: 'McDonald’s McAloo Tikki', calories: 320, protein: 8, carbs: 43, fats: 13, serving: '1 burger', baseQuantity: 1, unit: 'piece', category: 'Fast Food', isPackaged: true },
  { id: '70', name: 'French Fries', brand: 'McDonald’s Fries', calories: 312, protein: 3.4, carbs: 41, fats: 15, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Fast Food', isPackaged: true },
  { id: '71', name: 'Tomato Ketchup', brand: 'Kissan Tomato Ketchup', calories: 112, protein: 1.3, carbs: 26, fats: 0.1, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Condiments', isPackaged: true },
  { id: '72', name: 'Salted Peanuts', brand: 'Haldiram’s Salted Peanuts', calories: 585, protein: 24, carbs: 21, fats: 49, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Snacks', isPackaged: true },
  { id: '73', name: 'Bhujia', brand: 'Haldiram’s Aloo Bhujia', calories: 570, protein: 8.5, carbs: 50, fats: 38, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Packaged Snacks', isPackaged: true },
  { id: '74', name: 'Biscuit', brand: 'Parle-G', calories: 451, protein: 7.1, carbs: 76, fats: 13, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Snacks', isPackaged: true },
  { id: '75', name: 'Instant Oats', brand: 'Saffola Masala Oats', calories: 380, protein: 10, carbs: 63, fats: 9, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Packaged Breakfast', isPackaged: true },
  { id: '76', name: 'Dal Chawal', calories: 150, protein: 4.5, carbs: 26, fats: 3.1, serving: '100 g cooked', baseQuantity: 100, unit: 'g', category: 'Indian Staples' },
  { id: '77', name: 'Dal Makhani', calories: 168, protein: 5.2, carbs: 14.8, fats: 9.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '78', name: 'Paneer Tikka', calories: 210, protein: 14.5, carbs: 4.2, fats: 15, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '79', name: 'Butter Naan', calories: 310, protein: 8, carbs: 52, fats: 8, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Staples' },
  { id: '80', name: 'Garlic Naan', calories: 320, protein: 8.2, carbs: 54, fats: 8.2, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Staples' },
  { id: '81', name: 'Dhokla', calories: 160, protein: 6.2, carbs: 28, fats: 2.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Snacks' },
  { id: '82', name: 'Khandvi', calories: 180, protein: 5.5, carbs: 22, fats: 7.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Snacks' },
  { id: '83', name: 'Medu Vada', calories: 97, protein: 2.8, carbs: 11, fats: 4.8, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Breakfast' },
  { id: '84', name: 'Aloo Gobi', calories: 110, protein: 2.5, carbs: 12, fats: 6, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '85', name: 'Bhindi Masala', calories: 115, protein: 2.2, carbs: 11.5, fats: 7.2, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '86', name: 'Gajar Ka Halwa', calories: 282, protein: 4.2, carbs: 38, fats: 12.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '87', name: 'Rasmalai', calories: 180, protein: 5, carbs: 20, fats: 9, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Sweets' },
  { id: '88', name: 'Mango Lassi', calories: 110, protein: 2.8, carbs: 19, fats: 2.5, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Indian Drinks' },
  { id: '89', name: 'Shrikhand', calories: 260, protein: 6, carbs: 42, fats: 7.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '90', name: 'Jaljeera', calories: 15, protein: 0.2, carbs: 3.5, fats: 0.1, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Indian Drinks' },
  { id: '91', name: 'Green Tea', calories: 1, protein: 0, carbs: 0.2, fats: 0, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '92', name: 'Espresso', calories: 3, protein: 0.1, carbs: 0, fats: 0.2, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '93', name: 'Diet Coke', brand: 'Coca-Cola', calories: 0, protein: 0, carbs: 0, fats: 0, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Packaged Drinks', isPackaged: true },
  { id: '94', name: 'Bhel Puri', calories: 120, protein: 3.1, carbs: 22, fats: 2.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
  { id: '95', name: 'Sev Puri', calories: 230, protein: 4.8, carbs: 30, fats: 10, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
  { id: '96', name: 'Chana Masala', calories: 120, protein: 5.5, carbs: 17, fats: 3.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '97', name: 'Chicken Tikka', calories: 150, protein: 22, carbs: 3, fats: 5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '98', name: 'Egg Curry', calories: 145, protein: 9.8, carbs: 4.5, fats: 10, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '99', name: 'Methi Thepla', calories: 135, protein: 3.8, carbs: 21, fats: 4.2, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Breakfast' },
  { id: '100', name: 'Sabudana Khichdi', calories: 180, protein: 2, carbs: 38, fats: 3, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Breakfast' },
  { id: '101', name: 'Rice Kheer', calories: 145, protein: 3.2, carbs: 22, fats: 4.8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '102', name: 'Masala Oats', brand: 'Saffola', calories: 120, protein: 3.5, carbs: 21, fats: 2.5, serving: '100 g cooked', baseQuantity: 100, unit: 'g', category: 'Packaged Breakfast', isPackaged: true },
  { id: '103', name: 'Protein Bar', brand: 'RiteBite Max Protein', calories: 220, protein: 20, carbs: 22, fats: 6, serving: '1 bar', baseQuantity: 1, unit: 'piece', category: 'Supplements', isPackaged: true },
  { id: '104', name: 'Matcha Green Tea Latte', calories: 95, protein: 3.5, carbs: 12, fats: 3.5, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '105', name: 'Cold Coffee with Ice Cream', calories: 160, protein: 3, carbs: 22, fats: 7, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '106', name: 'Fresh Sugarcane Juice', calories: 80, protein: 0.2, carbs: 20, fats: 0, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Drinks' },
  { id: '107', name: 'Paneer Bhurji', calories: 190, protein: 12.8, carbs: 4.5, fats: 14, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '108', name: 'Soya Chunks Curry', calories: 155, protein: 16.5, carbs: 11, fats: 4.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Main Course' },
  { id: '109', name: 'Golgappa (Phuchka)', calories: 150, protein: 3, carbs: 25, fats: 4.5, serving: '5 pieces', baseQuantity: 5, unit: 'piece', category: 'Indian Street Food' },
  { id: '110', name: 'Suji Halwa (Sheera)', calories: 310, protein: 4.5, carbs: 54, fats: 8.5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Sweets' },
  { id: '111', name: 'Nimbu Paani (Shikanji)', calories: 35, protein: 0.2, carbs: 9, fats: 0.1, serving: '100 ml', baseQuantity: 100, unit: 'ml', category: 'Indian Drinks' },
    { id: '112', name: 'Soya Chaap Kebab', calories: 210, protein: 14, carbs: 8, fats: 12, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Fast Food' },
    { id: '113', name: 'Samosa', calories: 250, protein: 4, carbs: 30, fats: 12, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Fast Food' },
    { id: '119', name: 'Masala Puri', calories: 150, protein: 3, carbs: 30, fats: 5, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
    { id: '120', name: 'Dahi Bhalla', calories: 170, protein: 5, carbs: 20, fats: 8, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
    { id: '121', name: 'Aloo Bonda', calories: 210, protein: 4, carbs: 30, fats: 12, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
    { id: '122', name: 'Litti Chokha', calories: 250, protein: 7, carbs: 45, fats: 10, serving: '100 g', baseQuantity: 100, unit: 'g', category: 'Indian Street Food' },
    { id: '114', name: 'Aloo Tikki', calories: 180, protein: 3, carbs: 20, fats: 10, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Fast Food' },
    { id: '115', name: 'Pav Bhaji', calories: 300, protein: 7, carbs: 45, fats: 9, serving: '250 g', baseQuantity: 250, unit: 'g', category: 'Indian Fast Food' },
    { id: '116', name: 'Vada Pav', calories: 280, protein: 6, carbs: 40, fats: 10, serving: '1 piece', baseQuantity: 1, unit: 'piece', category: 'Indian Fast Food' },
    { id: '117', name: 'Masala French Fries', calories: 350, protein: 4, carbs: 45, fats: 15, serving: '150 g', baseQuantity: 150, unit: 'g', category: 'Indian Fast Food' },
    { id: '118', name: 'Paneer Wrap', calories: 260, protein: 12, carbs: 30, fats: 8, serving: '1 wrap', baseQuantity: 1, unit: 'piece', category: 'Indian Fast Food' },
];

export const HEALTHY_RECIPES: Recipe[] = [
  {
    id: 'r1',
    name: 'Greek Yogurt Fruit Bowl',
    prepTime: '5 min',
    calories: 280,
    protein: 18,
    description: 'A quick high-protein breakfast or snack with no cooking.',
    ingredients: ['200 g Greek yogurt', '1 banana sliced', '50 g berries', '10 g almonds'],
    steps: ['Add the yogurt to a bowl.', 'Top with sliced banana and berries.', 'Finish with chopped almonds and serve.'],
  },
  {
    id: 'r2',
    name: 'Simple Tofu Veg Stir-Fry',
    prepTime: '15 min',
    calories: 340,
    protein: 20,
    description: 'An easy protein-rich lunch using tofu and basic vegetables.',
    ingredients: ['150 g tofu', '100 g broccoli', '50 g bell pepper', '1 tsp oil', 'Soy sauce and pepper'],
    steps: ['Pan-sear the tofu until lightly golden.', 'Add vegetables and stir-fry for 4 to 5 minutes.', 'Season lightly and serve hot.'],
  },
  {
    id: 'r3',
    name: 'Oats Banana Smoothie',
    prepTime: '6 min',
    calories: 310,
    protein: 12,
    description: 'A simple filling smoothie for breakfast or post-workout.',
    ingredients: ['250 ml milk', '40 g oats', '1 banana', '1 tbsp peanut butter'],
    steps: ['Add all ingredients to a blender.', 'Blend until smooth.', 'Serve chilled or fresh.'],
  },
  {
    id: 'r4',
    name: 'Paneer Salad Wrap',
    prepTime: '12 min',
    calories: 390,
    protein: 22,
    description: 'A balanced wrap with paneer, vegetables, and easy prep.',
    ingredients: ['100 g paneer', '1 whole wheat wrap', 'Lettuce, onion, cucumber', 'Mint yogurt or light dressing'],
    steps: ['Lightly cook or grill the paneer.', 'Layer vegetables and paneer inside the wrap.', 'Roll tightly and serve.'],
  },
  {
    id: 'r5',
    name: 'Masala Egg Bhurji',
    prepTime: '10 min',
    calories: 250,
    protein: 16,
    description: 'Spiced scrambled eggs — a classic Indian high-protein breakfast.',
    ingredients: ['3 eggs', '1 small onion chopped', '1 tomato chopped', 'Green chilli, turmeric, salt', '1 tsp oil'],
    steps: ['Sauté onion and tomato with spices until soft.', 'Add beaten eggs and scramble on medium heat.', 'Serve hot with roti or toast.'],
  },
  {
    id: 'r6',
    name: 'Chickpea & Cucumber Salad',
    prepTime: '8 min',
    calories: 220,
    protein: 10,
    description: 'A refreshing no-cook salad packed with fiber and plant protein.',
    ingredients: ['150 g boiled chickpeas', '1 cucumber diced', '1 tomato diced', 'Lemon juice, chaat masala, salt'],
    steps: ['Combine chickpeas, cucumber, and tomato in a bowl.', 'Squeeze lemon juice and add chaat masala.', 'Toss well and serve chilled.'],
  },
  {
    id: 'r7',
    name: 'Overnight Oats',
    prepTime: '5 min + overnight',
    calories: 350,
    protein: 14,
    description: 'Prep the night before for a grab-and-go healthy breakfast.',
    ingredients: ['50 g rolled oats', '150 ml milk', '1 tbsp chia seeds', '1 tbsp honey', 'Fruit toppings'],
    steps: ['Mix oats, milk, chia seeds, and honey in a jar.', 'Refrigerate overnight for at least 6 hours.', 'Top with fresh fruit in the morning and enjoy.'],
  },
  {
    id: 'r8',
    name: 'Moong Dal Chilla',
    prepTime: '20 min',
    calories: 200,
    protein: 14,
    description: 'Savory lentil pancakes — a protein-rich Indian breakfast staple.',
    ingredients: ['100 g moong dal (soaked)', 'Ginger, green chilli', 'Onion, coriander leaves', 'Salt and cumin'],
    steps: ['Blend soaked moong dal into a smooth batter.', 'Mix in chopped onion, ginger, and spices.', 'Pour thin on a hot pan and cook both sides until golden.'],
  },
  {
    id: 'r9',
    name: 'Avocado Toast with Egg',
    prepTime: '8 min',
    calories: 320,
    protein: 15,
    description: 'Creamy avocado and a perfectly cooked egg on whole grain toast.',
    ingredients: ['1 slice whole wheat bread', '½ ripe avocado', '1 egg', 'Salt, pepper, chilli flakes'],
    steps: ['Toast the bread until crisp.', 'Mash avocado and spread on toast with salt and pepper.', 'Top with a fried or poached egg and chilli flakes.'],
  },
  {
    id: 'r10',
    name: 'Dal Khichdi',
    prepTime: '25 min',
    calories: 290,
    protein: 11,
    description: 'A comforting one-pot meal of rice and lentils — light and nutritious.',
    ingredients: ['50 g rice', '30 g moong dal', '1 tsp ghee', 'Turmeric, cumin, salt', 'Water'],
    steps: ['Wash rice and dal together.', 'Pressure cook with water, turmeric, and salt for 3 whistles.', 'Temper with ghee and cumin, then serve warm.'],
  },
  {
    id: 'r11',
    name: 'Quinoa Vegetable Bowl',
    prepTime: '20 min',
    calories: 380,
    protein: 14,
    description: 'A nutrient-dense grain bowl with roasted vegetables and a light dressing.',
    ingredients: ['80 g quinoa', '100 g mixed vegetables', '1 tbsp olive oil', 'Lemon juice, salt, herbs'],
    steps: ['Cook quinoa as per package instructions.', 'Roast or sauté vegetables with olive oil.', 'Combine in a bowl, drizzle lemon juice and herbs.'],
  },
  {
    id: 'r12',
    name: 'Sprouts Chaat',
    prepTime: '10 min',
    calories: 180,
    protein: 12,
    description: 'A tangy, crunchy snack loaded with protein from sprouted legumes.',
    ingredients: ['150 g mixed sprouts', '1 onion finely chopped', '1 tomato chopped', 'Lemon, chaat masala, coriander'],
    steps: ['Boil or steam sprouts until tender.', 'Mix with onion, tomato, and seasonings.', 'Squeeze lemon and garnish with coriander.'],
  },
  {
    id: 'r13',
    name: 'Banana Peanut Butter Bites',
    prepTime: '5 min',
    calories: 260,
    protein: 8,
    description: 'A no-cook energy snack — perfect for mid-day or pre-workout.',
    ingredients: ['2 bananas', '2 tbsp peanut butter', 'Cinnamon', 'Dark chocolate chips (optional)'],
    steps: ['Slice bananas into rounds.', 'Spread peanut butter between two slices to make sandwiches.', 'Sprinkle cinnamon and optional chocolate chips. Serve fresh or frozen.'],
  },
  {
    id: 'r14',
    name: 'Palak Poha',
    prepTime: '15 min',
    calories: 230,
    protein: 6,
    description: 'Spinach-infused flattened rice — a healthy twist on classic poha.',
    ingredients: ['100 g poha (flattened rice)', '50 g spinach puree', 'Peanuts, mustard seeds, curry leaves', 'Onion, green chilli, turmeric'],
    steps: ['Wash and soak poha for 2 minutes, then drain.', 'Temper mustard seeds, curry leaves, and peanuts in oil.', 'Add onion, spinach puree, turmeric, and poha. Mix well and serve.'],
  },
  {
    id: 'r15',
    name: 'Egg & Veggie Omelette',
    prepTime: '10 min',
    calories: 270,
    protein: 18,
    description: 'A fluffy, protein-packed omelette loaded with colorful vegetables.',
    ingredients: ['3 eggs', '30 g bell pepper diced', '20 g onion diced', '20 g spinach', 'Salt, pepper, 1 tsp butter'],
    steps: ['Whisk eggs with salt and pepper.', 'Sauté vegetables in butter for 2 minutes.', 'Pour eggs over vegetables and cook until set. Fold and serve.'],
  },
  {
    id: 'r16',
    name: 'Makhana Trail Mix',
    prepTime: '8 min',
    calories: 200,
    protein: 7,
    description: 'Roasted fox nuts with nuts and seeds — a guilt-free crunchy snack.',
    ingredients: ['50 g makhana (fox nuts)', '10 g almonds', '10 g pumpkin seeds', '1 tsp ghee', 'Salt, pepper, chaat masala'],
    steps: ['Dry roast makhana in ghee until crisp.', 'Toss in almonds and pumpkin seeds for a minute.', 'Season with salt and chaat masala. Cool and store.'],
  },
];

export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: 'h1',
    name: 'City General Hospital',
    rating: 4.5,
    reviews: 1240,
    distance: 1.2,
    status: 'open',
    address: '123 Health Ave, Medical District',
    lat: 12.9716,
    lng: 77.5946,
    emergency: true,
    phone: '+1 (555) 123-4567',
  },
  {
    id: 'h2',
    name: "St. Mary's Medical Center",
    rating: 4.2,
    reviews: 850,
    distance: 2.5,
    status: 'open',
    address: '456 Wellness Rd, North Side',
    lat: 12.9816,
    lng: 77.6046,
    emergency: true,
    phone: '+1 (555) 987-6543',
  },
  {
    id: 'h3',
    name: "Sunrise Children's Hospital",
    rating: 4.8,
    reviews: 620,
    distance: 3.8,
    status: 'open',
    address: '789 Care Lane, East Park',
    lat: 12.9616,
    lng: 77.5846,
    emergency: false,
    phone: '+1 (555) 444-3333',
  },
  {
    id: 'h4',
    name: 'Metropolitan Heart Institute',
    rating: 4.6,
    reviews: 2100,
    distance: 4.2,
    status: 'closed',
    address: '101 Pulse Blvd, South Gate',
    lat: 12.9516,
    lng: 77.5746,
    emergency: true,
    phone: '+1 (555) 222-1111',
  },
];
